### PR TITLE
Projects merging and renaming

### PR DESCRIPTION
**Pull request by phofman**
Here is another set of code updates understood as overall product refactoring. They were mostly driven by a company name change, but also include lots of changes indicated by ReSharper, Visual Studio's automatic analysis tools and my vision, how this all should go further. As a bonus, it also incorporates lots of bugfixes to the issues I found during testing.

Change log:
- removed all old XAML UIs and view-models as they were already improved by me (i.e. debug-token window, signing window, update-manager window)
- merged test projects into one
- merged add-in project with the package
- renamed the src/ folder into src_2010/, so all folders now look identical
- moved files with similar purpose into a folder (like: Editors/ will now contain all classes responsible for working bar-descriptor editor)
- renamed all the projects to follow new company name
- renamed all namespaces to follow new company name
- created new NativeCore project, that encapsulates only communication with BlackBerry NDK toolset (it doesn't provide any UI; the Package project is a layer between an NativeCore and VS UI now; this can be reused in future, in case other tools are required to build to help devs using pure MSBuild, also it speeds up testing)
- fixed not working bar-descriptor editor in VS2013 (as wrong library was loaded on systems with VS2010,VS2012,VS2013 installed)
- disabled scaling (stretching) of images in bar-descriptor editor, they now look much better
- added option to disable optimized-deployment for a project
- added tracking of NDK family (phone/tablet) and make the optimized-deployment disabled at runtime by default for PlayBook builds (so it's no more required to manually delete the app, before each upload)
- removed the need of having Java installed to have the deployment/signing/packaging to work (build-tasks will now consume the Java delivered by the bbndk_vs itself)
- MSBuild will now stop automatically at startup, when no installed NDK is detected with a respectful message (instead of failing a call to any BlackBerry tool with misleading info)
- fixed MSBuild crashes caused by custom build-tasks crashing in logs writing code
- latest installed NDK 10.0+ is automatically selected at plugin startup, if nothing selected before
- fixed improper registration of BlackBerry debug-engine on x86 machines
- fixed picked up location for bbt_id_rsa.pub by MSBuild custom tasks on Windows XP, as previously it was causing a failure, due to the whole folder non existence (now they share the location with Momentics)
- and other small tweaks.

All comments are welcome as always.

### CODE REVIEW

**Comment by phofman** [comment]
Could anybody please review and merge this stuff? I am progressing a lot o GDBParser front and I should be able to replace it by the mid of next week by my own C# implementation. And would be god to have the same codebase before, so you are not flooded with commits on next branch.

Thanks

**Comment by AndrewKnox** [comment]
Greetings Phofman! Dave is currently on vacation this week, and he won't be able to respond to your request until he returns. Sorry for the delay.

Cheers!

**Comment by phofman** [comment]
OK. No problem. Thanks for info.

**Comment by dbrgss** [comment]
Sorry Pawel...  for the delay.  Things have been CRAZY busy here... with vacations and other stuff.  Thanks for your contribution.

**Comment by phofman** [comment]
That's all fine. Cheers!

**Pull request merged**
