### PR TITLE
Moved plugin UI to the next level

### PR DESCRIPTION
**Pull request by phofman**
Spent some time optimizing probably the most frustrating part of the plugin - the UI (look and freezes).
From the visual point of view it should present itself and work more like a stable product. Please let me know, what do you think.

Change log:
- plugin doesn't warm up for 20 secs now (yes, in PL downloading list of available API Levels took that time; even if this info was not used by developer, he was forced to wait)
- reimplemented calls to BlackBerry native tools - now they are called asynchronously and return parsed info as read-only object - much more data is displayed and VS doesn't hang anymore
- removed hardcoded paths to used QNX toolset (also some cleaning was done to encapsulate access to external things like registry and files, so maintaining this code should be much easier now)
- removed custom 'dialogs' and introduced regular Visual Studio settings pages with support of a [Cancel] button, that reverts all the changes
- added option to add 'custom NDK' based on paths to host/target folders (useful probably only to people using more frequent NDK builds than Gold)
- added support of having 1+ devices and simulators defined and switch them as easy as possible
- added feature to generate and deploy debug-token with 1+ PIN
- added option to remove stored CSK password from registry
- added plugin-dedicated output window (View -> Output -> select [BlackBerry]), to keep track of runtime logs - I want to use it to push GDB logs there too
- improved main-menu (added more sections, links to documentation&samples and about window with references to the project and bug-tracker)
- all changes are backward compatible (that means - at the end of the day, they update the same registry fields etc. as before I did the refactoring)
- and others I've seen useful...

NOTEs:
- During the review - could anybody please verify, if registration and un-registration developer certificate works? On my 2 machines - the 'new' nor the 'old' version don't generate any csk file. Maybe there is a better way of doing this (something from Momentics?), that doesn't still cookies and a silent HTTP-Request etc...
- In next step I will remove the 'old' settings stuff completely (code, UI, menu, tests).
- Downloading API Levels is not done yet. Do you think it's really needed? Especially if the plugin detects installed NDKs.

Menus & Output Window
Targets
Signing
API Levels

BR

### CODE REVIEW

**Comment by phofman** [comment]
Just pushed some extra fixes. Hope this doesn't break and make your review restarted.  
Main changes:
- improved the build and setup commands - to actually make the testing on several virtual machines easy
- fixed few exceptions thrown, causing Visual Studio to terminate
- totally redesigned developer's registration - the one implemented in this repo before was not working at all, now you can generate BlackBerry ID tokens with few clicks
- added support of BlackBerry PlayBook signing credentials etc
- added support of 32-bit OSes (Windows XP, Windows 7 x86 in particular)
- improved detection of already installed NDKs
- added option to open tutorials/samples/documentation within Visual Studio's build-in browser
- displaying info about developer's .p12 certificate and tokens  
  and all the other small tweaks...

**Comment by dbrgss** [comment]
Good Morning Pawel..

Sorry about the delay...  Things have been busy..  I am reviewing your pull request and should be able to pull it in the next day or so.  You have made some pretty impressive changes and have done alot of things that I would have loved to have accomplished earlier.  Will be commenting is future comments below..

Dave

**Comment by dbrgss** [comment]
plugin doesn't warm up for 20 secs now (yes, in PL downloading list of available API Levels took that time; even if this info was not used by developer, he was forced to wait)

The reason for front loading this at plugin startup was to avoid having a user wait that time when they try to enter the API Level dialog.  I do see your point that front loading puts an unnecessary wait time on users that don't need to use this feature.  The issue lies in the perception when a user clicks on the dialog and it waits 20 seconds.. that the plugin is hanging.  People are more forgiving waiting a period of time during startup as opposed to during usage.   If you can think of a good way to mitigate the idea that the plugin is hanging it would be great.

**Comment by phofman** [comment]
Hi Dave,

Yes, I do understand the reasoning partially. My biggest problem is that developer doesn't need the available API-Level list each time (s)he loads the project ;)

I have the idea, how to improve the thing (i.e. the overall NDK installation). What I think could do the job - is making the dialogs displayed immediatelly and loading data async. Dev will see that something is running and simply will wait, only once, then the list could be cached;
Also:
- plugin detects already installed BlackBerry NDKs (installed via Momentics) and could suggest using them (but not allow to uninstall)
- there are 2 lists loaded from the server ('--list' and '--list-all'; I suspect one should be enough to present the data on UI, that should at least reduce the wait time by half)
- there should be an option to make the installation in background, without blocking Visual Studio itself; and in case it's ongoing, the build process should simply exit with error

I created new branch today to implement it, so expect new pull request in few days.

**Comment by phofman** [comment]
Some notes from top of my mind for reviewer:
- **my** part of 'developer registration' more strictly follows the Momentics, where the author.p12 cert and .csk files should be located; so to have it fully running with existing 'registration' dialogs, you might need to copy them manually on some platforms (especially Windows XP)
- there are lots of errors, when opening any developer.blackberry.com websites within the Visual Studio (no matter which version) about missing methods/fields/etc. in JavaScripts; maybe you could report it somewhere inside the company, so it gets fixed one day :) ? - that's why I left an option to open them in external web-browser, as it was quite painfull to use...
- automated tests do rather basic job; let me know, if you would like to have something more complicated (like UI-tests or something)

**Comment by dbrgss** [comment]
Not sure I understand your question here.. 

Downloading API Levels is not done yet. Do you think it's really needed? Especially if the plugin detects installed NDKs.

API Levels are the same as NDK's...  There is still a need to download new API Levels/NDK's  

Sorry maybe I am not understanding you correctly.. :-)

Dave

**Comment by phofman** [comment]
My intention here was to say, I haven't yet refactored the 'UpdateManager', by doing it async and introducing **new** screens etc. And was wondering, if this functionality is really needed as dev can install NDKs separately and just 'add' them on rely on auto-detection.

But yeah, after two weeks I understand it's a nice feature and as said, I am working on it right now.

**Pull request merged**
